
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - job.vr.fmwk.com
  resources:
  - vrtestjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - job.vr.fmwk.com
  resources:
  - vrtestjobs/finalizers
  verbs:
  - update
- apiGroups:
  - job.vr.fmwk.com
  resources:
  - vrtestjobs/status
  verbs:
  - get
  - patch
  - update
