# permissions for end users to edit vrtestjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vrtestjob-editor-role
rules:
- apiGroups:
  - job.vr.fmwk.com
  resources:
  - vrtestjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - job.vr.fmwk.com
  resources:
  - vrtestjobs/status
  verbs:
  - get
